# Generated by Django 2.0.2 on 2018-02-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w40k', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wargearlist',
            name='name',
            field=models.CharField(choices=[('Ranged', 'Ranged'), ('Special', 'Special'), ('Heavy', 'Heavy'), ('Melee', 'Melee')], max_length=60),
        ),
    ]
