# Generated by Django 2.0.2 on 2018-02-21 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('w40k', '0002_extend_char_limit_on_wargear_list_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArmyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ArmyModelItemSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, help_text='Amount of identical! items in this slot.')),
                ('army_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w40k.ArmyModel')),
                ('item', models.ForeignKey(help_text='Equipped item(s).', on_delete=django.db.models.deletion.CASCADE, to='w40k.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ArmyUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('army', models.ForeignKey(help_text='The army this unit is part of.', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='w40k.Army')),
                ('models', models.ManyToManyField(help_text='The particular models (e.g. configurations present in this unit.', to='w40k.ArmyModel')),
                ('unit', models.ForeignKey(help_text="The 'unittemplate' this unit is an instance of.", on_delete=django.db.models.deletion.CASCADE, to='w40k.Unit')),
            ],
        ),
        migrations.AlterField(
            model_name='wargearlist',
            name='name',
            field=models.CharField(choices=[('Ranged', 'Ranged'), ('Special', 'Special'), ('Heavy', 'Heavy'), ('Melee', 'Melee'), ('Vehicle Equipment', 'Vehicle Equipment')], max_length=60),
        ),
        migrations.AlterField(
            model_name='weaponprofile',
            name='attack_type',
            field=models.CharField(choices=[('Pistol', 'Pistol'), ('Grenade', 'Grenade'), ('Rapid Fire', 'Rapid Fire'), ('Assault', 'Assault'), ('Heavy', 'Heavy'), ('Melee', 'Melee')], help_text='This specifies which attack specific extra rules apply.', max_length=20),
        ),
        migrations.AddField(
            model_name='armymodel',
            name='itemslots',
            field=models.ManyToManyField(help_text='The specific itemslot configuration for this model.', through='w40k.ArmyModelItemSlot', to='w40k.Item'),
        ),
        migrations.AddField(
            model_name='armymodel',
            name='model',
            field=models.ForeignKey(help_text="The 'generic unit model' that is the 'template' for this specific model.", on_delete=django.db.models.deletion.CASCADE, to='w40k.UnitModel'),
        ),
        migrations.AddField(
            model_name='armymodel',
            name='unit',
            field=models.ForeignKey(help_text='The specific army unit this model is part of.', on_delete=django.db.models.deletion.CASCADE, to='w40k.ArmyUnit'),
        ),
    ]
