# Generated by Django 2.0.2 on 2018-02-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w40k', '0003_add_army_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponprofile',
            name='attack_type',
            field=models.CharField(choices=[('Melee', 'Melee'), ('Pistol', 'Pistol'), ('Rapid Fire', 'Rapid Fire'), ('Assault', 'Assault'), ('Heavy', 'Heavy'), ('Grenade', 'Grenade')], help_text='This specifies which attack specific extra rules apply.', max_length=20),
        ),
    ]
