# Generated by Django 2.0.2 on 2018-02-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('w40k', '0004_auto_20180221_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmodel',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='w40k.Unit'),
        ),
    ]
