# Generated by Django 2.0.2 on 2018-02-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w40k', '0005_unitmodel_unit_related_name_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmodel',
            name='max_amount',
            field=models.PositiveIntegerField(default=0, help_text='How many models with this specific setup may the parent unit include at maximum?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitmodel',
            name='min_amount',
            field=models.PositiveIntegerField(default=0, help_text='How many models with this specific setup must the parent unit include at least?'),
            preserve_default=False,
        ),
    ]
