# Generated by Django 2.0.2 on 2018-02-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w40k', '0006_add_unit_model_min_max_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmodel',
            name='name_suffix',
            field=models.CharField(blank=True, help_text='Identifier for this particular configuration.', max_length=80),
        ),
    ]
