# Generated by Django 2.0.2 on 2018-02-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w40k', '0007_unitmodel_add_name_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armyunit',
            name='models',
        ),
    ]
