# Generated by Django 2.0.2 on 2018-02-24 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('w40k', '0008_remove_armyunit_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armymodel',
            name='unit',
            field=models.ForeignKey(help_text='The specific army unit this model is part of.', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='w40k.ArmyUnit'),
        ),
    ]
