# Generated by Django 2.0.2 on 2018-02-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w40k', '0009_rename_army_model_unit_related_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weaponprofile',
            name='_strength_multiplier',
        ),
        migrations.RemoveField(
            model_name='weaponprofile',
            name='_strength_user',
        ),
        migrations.RemoveField(
            model_name='weaponprofile',
            name='_strength_value',
        ),
        migrations.AddField(
            model_name='weaponprofile',
            name='strength_max',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weaponprofile',
            name='strength_min',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
