# Generated by Django 2.0.2 on 2018-02-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w40k', '0010_refactor_weapon_profile_strength_to_min_max_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weaponprofile',
            name='_damage_dice_amount',
        ),
        migrations.RemoveField(
            model_name='weaponprofile',
            name='_damage_die_type',
        ),
        migrations.RemoveField(
            model_name='weaponprofile',
            name='_damage_value',
        ),
        migrations.AddField(
            model_name='weaponprofile',
            name='damage_max',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weaponprofile',
            name='damage_min',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
