# Generated by Django 2.0.2 on 2018-02-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w40k', '0011_refactor_weapon_profile_damage_to_min_max_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weaponprofile',
            name='number_of_attacks',
        ),
        migrations.AddField(
            model_name='weaponprofile',
            name='number_of_attacks_max',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weaponprofile',
            name='number_of_attacks_min',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
