# Generated by Django 2.0.2 on 2018-02-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w40k', '0012_refactor_weapon_profile_number_of_attacks_to_min_max_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weaponprofile',
            old_name='max_range',
            new_name='range_max',
        ),
        migrations.RenameField(
            model_name='weaponprofile',
            old_name='min_range',
            new_name='range_min',
        ),
    ]
