# Generated by Django 2.0.2 on 2018-02-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w40k', '0013_rename_weapon_profile_range_min_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armyunit',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
