# Generated by Django 2.0.2 on 2018-02-25 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w40k', '0014_remove_unique_from_army_unit_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wargearlist',
            unique_together={('name', 'organization')},
        ),
    ]
